#Name of the Workflow
name: Start Release

#Disparador del proceso
on:
  push:
    tags:
       - "v*"


#Crear automaticamente el release
jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
