name: Update Changelog After Release

# Disparador: Cuando se publica un release
on:
  release:
    types:
      - published

jobs:
  update_changelog:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Asegura que todos los commits y etiquetas estén disponibles

      # 2. Generar y actualizar el archivo de changelog
      - name: Generate and Commit Changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: CHANGELOG.md           # Archivo que contendrá el changelog
          preset: angular                    # Usar formato de commits convencionales (Angular preset)
          commit-message: "chore: update changelog after release"  # Mensaje del commit
          skip-empty: false                  # No ignorar releases vacíos
          skip-unstable: false               # Incluir commits de versiones preliminares (si aplica)
          dry-run: false                     # Generar y aplicar cambios directamente

      # 3. Mostrar el changelog en los logs para depuración (opcional)
      - name: Display Changelog
        run: cat CHANGELOG.md
