name: Auto Generate Chanelog
on:
  release:
    types: [created, edited]

    
jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: ${{ secrets.KEY_SECRET }}
          # skip-version-file: 'true'
